CREATE TABLE T_USER(
	id VARCHAR2(20) PRIMARY KEY,
	pwd VARCHAR2(100) NOT NULL,
	name VARCHAR2(30),
	phone VARCHAR2(30),
	email VARCHAR2(50),
	addr VARCHAR2(100),
	regdate DATE DEFAULT SYSDATE
);